### ISSUE TITLE
ApiQueryLog somehow asks for datasources that doesn't exist

### ISSUE THREAD

**Issue by Spriz** [FriendsOfCake/crud#341]
In my cake 3.0.15 project we have different datasources: `default`, `test` and `alpha`.

If I enable Crud like this:
```
$this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.Add',
                'Crud.Edit',
                'Crud.View',
                'Crud.Delete'
            ],
            'listeners' => [
                'Crud.Api',
                'Crud.ApiPagination',
                'Crud.ApiQueryLog'
            ]
        ]);
```

and in my Integration test uses following:

```
$this->get('someUrl/:id);
$this->assertResponseOk();
```

I get the following error:

```
PHPUnit 5.0.8 by Sebastian Bergmann and contributors.


Starting test 'Api\Test\TestCase\Controller\WallPostsControllerTest::testIndex'.
F                                                                   1 / 1 (100%)

Time: 473 ms, Memory: 17.00Mb

There was 1 failure:

1) Api\Test\TestCase\Controller\WallPostsControllerTest::testIndex
exception 'Cake\Datasource\Exception\MissingDatasourceConfigException' with message 'The datasource configuration "test_alpha" was not found.' in /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php:187
Stack trace:
#0 /var/www/dev/apacta-2/vendor/friendsofcake/crud/src/Listener/ApiQueryLogListener.php(109): Cake\Datasource\ConnectionManager::get('alpha')
#1 /var/www/dev/apacta-2/vendor/friendsofcake/crud/src/Listener/ApiQueryLogListener.php(51): Crud\Listener\ApiQueryLogListener->_getSource('alpha')
#2 /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Event/EventManager.php(385): Crud\Listener\ApiQueryLogListener->setupLogging(Object(Cake\Event\Event))
#3 /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Event/EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#4 /var/www/dev/apacta-2/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php(505): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#5 /var/www/dev/apacta-2/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php(191): Crud\Controller\Component\CrudComponent->trigger('beforeFilter')
#6 /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Event/EventManager.php(385): Crud\Controller\Component\CrudComponent->beforeFilter(Object(Cake\Event\Event))
#7 /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Event/EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Controller/Controller.php(474): Cake\Controller\Controller->dispatchEvent('Controller.init...')
#10 /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(Api\Controller\WallPostsController))
#12 /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestCase.php(272): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\TestSuite\Stub\Response))
#13 /var/www/dev/apacta-2/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestCase.php(184): Cake\TestSuite\IntegrationTestCase->_sendRequest(Array, 'GET')
#14 /var/www/dev/apacta-2/plugins/Api/tests/TestCase/Controller/WallPostsControllerTest.php(105): Cake\TestSuite\IntegrationTestCase->get(Array)
#15 [internal function]: Api\Test\TestCase\Controller\WallPostsControllerTest->testIndex()
#16 /var/www/dev/apacta-2/vendor/phpunit/phpunit/src/Framework/TestCase.php(908): ReflectionMethod->invokeArgs(Object(Api\Test\TestCase\Controller\WallPostsControllerTest), Array)
#17 /var/www/dev/apacta-2/vendor/phpunit/phpunit/src/Framework/TestCase.php(771): PHPUnit_Framework_TestCase->runTest()
#18 /var/www/dev/apacta-2/vendor/phpunit/phpunit/src/Framework/TestResult.php(617): PHPUnit_Framework_TestCase->runBare()
#19 /var/www/dev/apacta-2/vendor/phpunit/phpunit/src/Framework/TestCase.php(727): PHPUnit_Framework_TestResult->run(Object(Api\Test\TestCase\Controller\WallPostsControllerTest))
#20 /var/www/dev/apacta-2/vendor/phpunit/phpunit/src/Framework/TestSuite.php(747): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#21 /var/www/dev/apacta-2/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(425): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#22 /var/www/dev/apacta-2/vendor/phpunit/phpunit/src/TextUI/Command.php(154): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#23 /var/www/dev/apacta-2/vendor/phpunit/phpunit/src/TextUI/Command.php(105): PHPUnit_TextUI_Command->run(Array, true)
#24 /var/www/dev/apacta-2/vendor/phpunit/phpunit/phpunit(47): PHPUnit_TextUI_Command::main()
#25 {main}

/var/www/dev/apacta-2/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestCase.php:469
/var/www/dev/apacta-2/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestCase.php:408
/var/www/dev/apacta-2/plugins/Api/tests/TestCase/Controller/WallPostsControllerTest.php:106
```

The string `'test_alpha'` doesn't exist in our project, neither have it ever appeared as a data source :disappointed: 

Any clue where I should look for mistakes?

**Comment by josegonzalez** [comment]
Are you potentially sharing the same cache (file, memcached, apc) across multiple projects?

**Comment by Spriz** [comment]
@josegonzalez I just tried clearing my cache (Redis) and it didn't help and it's a vagrant machine with one isolated cake3 app

**Comment by lorenzo** [comment]
This is actually a bug @Spriz... would you like to fix it? The fix is to try/catch the exception in the listener and just ignore it

**Comment by Spriz** [comment]
like #342 @lorenzo ?

**Comment by steefaan** [comment]
I noticed this issue also a few times but at the end it was always an issue in my application. @lorenzo Not sure if we should catch the exception here.

**Comment by Spriz** [comment]
Closing because of #347
