### ISSUE TITLE
Recursion within the trace when using listener Crud.Api

### ISSUE THREAD

**Issue by rdcx** [FriendsOfCake/crud#456]
Any standard 500 error like "Call to a member function find() on boolean" is generating a stack trace with recursions...

This only occurs when debug > 0

```
App\Controller\ExampleController Object
(
    [name] => Examples
    [helpers] => Array
        (
        )
    [_components:protected] => Cake\Controller\ComponentRegistry Object
        (
            [_Controller] => App\Controller\ExampleController Object
 *RECURSION*
```

**Comment by jippi** [comment]
is this a problem or a statement ? :) 

if its a problem, why is it a problem ?

**Comment by ross-chater** [comment]
lol its a problem, the recursion causes an error with serialization 

```
"trace": [
      {
        "file": "/pathtomyproject/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php",
        "line": 126,
        "function": "handleFatalError",
        "class": "Cake\\Error\\BaseErrorHandler",
        "type": "->",
        "args": [
          256,
          "[RuntimeException] Serialization of View data failed.\n#0 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/View/JsonView.php(107): Cake\\View\\SerializedView->render('error500', 'error')\n#1 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(356): Cake\\View\\JsonView->render('error500', 'error')\n#2 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(335): Cake\\Error\\ExceptionRenderer->_outputMessageSafe('error500')\n#3 /var/www/pathtomyproject/vendor/friendsofcake/crud/src/Error/ExceptionRenderer.php(76): Cake\\Error\\ExceptionRenderer->_outputMessage('error')\n#4 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(192): Crud\\Error\\ExceptionRenderer->_outputMessage('error')\n#5 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(144): Cake\\Error\\ExceptionRenderer->render()\n#6 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(179): Cake\\Error\\ErrorHandler->_displayException(Object(Cake\\Error\\PHP7ErrorException))\n#7 /var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(163): Cake\\Error\\BaseErrorHandler->handleException(Object(Cake\\Error\\PHP7ErrorException))\n#8 [internal function]: Cake\\Error\\BaseErrorHandler->wrapAndHandleException(Object(Cake\\Error\\PHP7ErrorException))\n#9 {main}",
          "/var/www/pathtomyproject/vendor/cakephp/cakephp/src/Error/ErrorHandler.php",
          156
        ]
      },
      { 
```

**Comment by ross-chater** [comment]
https://github.com/FriendsOfCake/crud/blob/master/src/Error/ExceptionRenderer.php#L103

getTrace() 

This is where I've traced it back to, I'm literally crawling through packages and frameworks loosing all my marbles.

**Comment by bravo-kernel** [comment]
@ross-chater friendly ping, can you provide more information of can this ticket be closed?
